- name: configuring mongodb server
  hosts: mongodb
  become: yes
  tasks:
      - name: copying mongo.repo
        copy:
          src: mongo.repo
          dest:  /etc/yum.repos.d/mongo.repo

      - name: installing mongodb
        package:
           name: mongodb-org
           state: present

      - name: replace and allowing remote connections
        replace:
           path: /etc/mongod.conf
           regexp: '127.0.0.1'
           replace: '0.0.0.0'     

      - name: start and enable service
        service:
            name: mongod
            state: started
            enabled: yes