[local]
localhost

[mongodb]
mongodb.devopsonline.online

[redis]
redis.devopsonline.online

[mysql]
mysql.devopsonline.online

[rabbitmq]
rabbitmq.devopsonline.online

[catalogue]
catalogue.devopsonline.online

[user]
user.devopsonline.online

[cart]
cart.devopsonline.online

[shipping]
shipping.devopsonline.online

[payment]
payment.devopsonline.online

[frontend]
frontend.devopsonline.online

[private-key-demo]
172.31.37.172